services:
  nginx:
    image: cristianmazzarone/ctf_nginx:latest
    ports:
      - 8080:80

  php:
    image: cristianmazzarone/ctf_php:latest

  others:
    image: cristianmazzarone/ctf_others:latest
    ports:
      - 2222:22

  db:
    image: cristianmazzarone/ctf_postgres:latest
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
